/*Este código se encarga de crear un view con información requerida
para el análisis de la data de Emails de Hubspot*/
--Desarrollado por Sebastián Navarrete
--Data Cloud Engineer
--Interlat Colombia

-- CONFIGURACIÓN DE ENTORNO DE TRABAJO
USE ROL ACCOUNTADMIN;      --usar el rol 'ACCOUNTADMIN'
USE WAREHOUSE INTERLAT_WH; --usar el warehouse 'INTERLAT_WH'
USE DATABASE INTERLAT_DB;  --usar la base de datos 'INTERLAT_DB'
USE SCHEMA MARKETING;      --usar el esquema 'MARKETING'

-- UNION DE TABLAS
CREATE OR REPLACE VIEW EMAIL_DATA_POWERBI AS
SELECT EE.CREATED AS DATE, EE.TYPE, SUB.SUBJECT, ES."FROM", EE.RECIPIENT, EC.NAME AS CAMPAIGN_NAME, LOC.LOCATION
FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT AS EE
FULL JOIN INTERLAT_DB.HUBSPOT.EMAIL_EVENT_SENT AS ES ON EE.ID = ES.ID
FULL JOIN INTERLAT_DB.HUBSPOT.EMAIL_CAMPAIGN AS EC ON EE.EMAIL_CAMPAIGN_ID = EC.ID
FULL JOIN (
SELECT ID, LOCATION FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_OPEN
UNION
SELECT ID, LOCATION FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_CLICK
UNION
SELECT ID, LOCATION FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_FORWARD
UNION
SELECT ID, LOCATION FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_PRINT) AS LOC ON EE.ID = LOC.ID
FULL JOIN(
SELECT ID, SUBJECT FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_SENT
UNION
SELECT ID, SUBJECT FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_SUPPRESSED
UNION
SELECT ID, SUBJECT FROM INTERLAT_DB.HUBSPOT.EMAIL_EVENT_DROPPED) AS SUB ON EE.ID = SUB.ID;

SELECT * FROM EMAIL_DATA_POWERBI LIMIT 120;